### ISSUE TITLE
Segmentation fault using "define" and "text"?

### ISSUE THREAD

**Issue by guidoBenvenuto** [jrincayc/ucblogo-code#104]
The following  example (adapted from CSLS, second volume, pg 74-75) does not work using UCBLogo 6.2, Windows 10.

Welcome to Berkeley Logo version 6.2
? define "example [[] [print "first] [print "last]]
? example
first
last

But if the following is defined

? define "example lput [print "new] butlast text "example

UCB Logo exits (with a segmentation fault?).

Thank you.
Guido Gay

**Comment by brianharvey** [comment]
Thanks for reporting this.

The error seems to be an infinite loop in deep_copy.  Importantly, it doesn't happen if the second DEFINE is done _without_ first running the procedure.  So I'm guessing the problem is that the definition has been treeified before taking its butlast.  Untreeifying it before copying when BUTLAST is called should fix it.

The crash happens on the second DEFINE, before even trying to run the new procedure.  And if you give the new one a different name, that doesn't change the behavior.

I'll try an experiment with the code to see if I'm right...

**Comment by brianharvey** [comment]
Hmm, what am I doing wrong:

bhpro13.Home% autoconf
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:24: error: possibly undefined macro: AC_DEFINE
configure.ac:25: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:43: error: possibly undefined macro: AM_COND_IF
configure.ac:87: error: possibly undefined macro: AC_SEARCH_LIBS
configure.ac:101: error: possibly undefined macro: AC_CHECK_HEADERS
bhpro13.Home%

**Comment by brianharvey** [comment]
Oh, the change I was trying to make was to change line 78 of lists.c from
`args = arg`
to
`args = untreeify(arg)`

**Comment by dmalec** [comment]
@brianharvey if I run `autoconf` on a fresh checkout, I see the same thing. The initial step I use on fresh checkout is `autoreconf --install`.

**Comment by brianharvey** [comment]
Ah, thanks.  That makes it compile, but alas, my proposed fix didn't fix the problem.  :(  Back to the drawing board.

**Comment by jrincayc** [comment]
Stack trace on Linux (for posterity):
```
(gdb) where 10
#0  0x000000000041b1b6 in deep_copy (expresn=0x0) at eval.c:283
#1  0x000000000041b201 in deep_copy (expresn=0x7f12d23cd920) at eval.c:285
#2  0x000000000041b201 in deep_copy (expresn=0x7f12d23cd8e0) at eval.c:285
#3  0x000000000041b224 in deep_copy (expresn=0x7f12d23ce520) at eval.c:286
#4  0x000000000041b224 in deep_copy (expresn=0x7f12d23cd920) at eval.c:286
#5  0x000000000041b201 in deep_copy (expresn=0x7f12d23cd8e0) at eval.c:285
#6  0x000000000041b224 in deep_copy (expresn=0x7f12d23ce520) at eval.c:286
#7  0x000000000041b224 in deep_copy (expresn=0x7f12d23cd920) at eval.c:286
#8  0x000000000041b201 in deep_copy (expresn=0x7f12d23cd8e0) at eval.c:285
#9  0x000000000041b224 in deep_copy (expresn=0x7f12d23ce520) at eval.c:286
(More stack frames follow...)
(gdb) where -10
#174591 0x000000000041b201 in deep_copy (expresn=0x7f12d23cdbe0) at eval.c:285
#174592 0x000000000041b224 in deep_copy (expresn=0x7f12d23ce460) at eval.c:286
#174593 0x000000000041b20d in deep_copy (expresn=0x7f12d23cc1a0) at eval.c:285
#174594 0x000000000041b201 in deep_copy (expresn=expresn@entry=0x7f12d23cc1e0)
    at eval.c:285
#174595 0x00000000004350c4 in define_helper (args=0x7f12d23cc8a0, macro_flag=0)
    at wrksp.c:233
#174596 0x000000000041c7f3 in evaluator
    (list=0x7f12d23cd660, where=<optimized out>) at eval.c:660
#174597 0x000000000042d84e in start
    (argc=<optimized out>, argv=<optimized out>) at main.c:356
#174598 0x0000000000441983 in LogoApplication::OnRun() (this=<optimized out>)
    at wxTerminal.cpp:269
#174599 0x00007f12fa02b6f0 in wxEntry(int&, wchar_t**) ()
    at /lib64/libwx_baseu-3.0.so.0
#174600 0x0000000000417b62 in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>) at wxMain.cpp:29

```
