### ISSUE TITLE
Building latest UCB Logo on mac os still crashes when invoking edit.

### ISSUE THREAD

**Issue by JTurco32** [jrincayc/ucblogo-code#115]
Hello,
after reading the instructions here (thank you for that!) to get the latest ucblogo working on MAC OS with wxWidgets, i still get the issue where logo crashes when invoking the edit command. I know this was an issue with Brian harvey's last release, is this still an issue with the latest? Im running MAC OS Catalina if that helps. Many thanks.

**Comment by dmalec** [comment]
Hello @JTurco32,

Glad you were able to get logo compiling on Mac OS. I did try a clean build today and didn't see the issue with `EDIT` or `EDALL`; but, let me capture specifically what I ran so we can see if it's something in build environments / steps (I'm running Catalina 10.15.7):

Having downloaded wxWidgets and uncompressed it:
```
cd wxWidgets-3.0.5
mkdir build-cocoa-static
cd build-cocoa-static
../configure --enable-debug --disable-shared --with-macosx-version-min=10.14
make -j6
cd ..
git clone https://github.com/jrincayc/ucblogo-code.git
cd ucblogo-code
autoreconf --install
./configure --prefix=$HOME/ucblogo_install --with-wx-config=$HOME/wxWidgets-3.0.5/build-cocoa-static/wx-config --disable-docs
make -j6 mac
UCBLogo.app/Contents/MacOS/UCBLogo
```

**Comment by JTurco32** [comment]
that did the trick. mabye i missed a flag. didn't use the `--with-macosx-version-min=10.14` flag so mabye thats what i needed to do. many thanks :)

**Comment by dmalec** [comment]
You're welcome, no worries - glad to hear that solved it :)
