### ISSUE TITLE
Backtick not working???

### ISSUE THREAD

**Issue by gypsydave5** [jrincayc/ucblogo-code#117]
I'm running the latest release of UCBLogo on MacOS, using wxWidgets.

input:
```
show `[foo baz ,[bf [a b c]] garply ,@[bf [a b c]]]
```

expected output:
```
[foo baz [b c] garply b c]
```

actual output:
```
I don't know how  to `
```

This also makes itself apparent when trying to use `cascade`.

**Comment by dmalec** [comment]
A little bit of research.

I can reproduce this on MacOS with wxWidgets.

 If I run this on Windows, MacOS **without** wxWidgets, or Linux, the above command runs as expected.
