### ISSUE TITLE
and True False returns True

### ISSUE THREAD

**Issue by stoverc** [jrincayc/ucblogo-code#124]
`and True False ` when it should return `False`.

<img width="1073" alt="Screen Shot 2022-01-30 at 7 31 42 PM" src="https://user-images.githubusercontent.com/6565018/151724526-7add0ff8-44da-4d6e-908c-28b954b80cb6.png">

**Comment by stoverc** [comment]
Similarly, `(and true false false)` returns `true`.

**Comment by jrincayc** [comment]
We can get the expected behavior if we do:
```
make "true (1 = 1)
make "false (1 = 0)
```
Then:
```
? and true false
You don't say what to do with false
? (and true false false)
You don't say what to do with false
```

**Comment by jrincayc** [comment]
I didn't see anywhere in the documentation saying that we define true and false. @brianharvey  Any opinion on if we should add true and false to the initial environment?

**Comment by stoverc** [comment]
It doesn't directly say they're defined, but it does say there's a special meaning for them:

<img width="799" alt="Screen Shot 2022-01-30 at 8 22 33 PM" src="https://user-images.githubusercontent.com/6565018/151726901-112c97f7-0162-4b3d-b42b-380938371d81.png">

Not sure if that matters or not, but it **is** somewhat suggestive.

**Comment by stoverc** [comment]
It doesn't say they're defined, per se, but it **does** say they're "special":

<img width="799" alt="Screen Shot 2022-01-30 at 8 22 33 PM" src="https://user-images.githubusercontent.com/6565018/151727093-57216136-e2da-4ea0-bcb5-13215b559a66.png">

Clearly not a definitive thing, but it **is** somewhat suggestive.

**Comment by brianharvey** [comment]
On 1/30/22 5:16 PM, Joshua Cogliati wrote:
> I didn't see anywhere in the documentation saying that we define true and false. @brianharvey  Any opinion on if we should add true and false to the initial environment?

I don't have a strong opinion either way, but those examples would have 
worked if the words were quoted (like any other situation in which you 
want a literal word as an input):  AND "TRUE "FALSE and so on.

**Comment by stoverc** [comment]
Ahhhh, this makes sense. I apologize for my ignorance; I'm new to Logo (just got it a couple days ago to expose my son to some programming stuff) so I'm pretty unsure about a lot of things like this.

Thanks for entertaining my situation, and I'm sorry for wasting everyone's time.

**Comment by jrincayc** [comment]
Hm, maybe we should add some examples in the logical operations section of the manual with "true and "false.

**Comment by stoverc** [comment]
That definitely wouldn't hurt. 👍
