### ISSUE TITLE
Numerous build warnings

### ISSUE THREAD

**Issue by pmetzger** [jrincayc/ucblogo-code#132]
The enclosed messages are on MacOS Monterey and wxWidgets 3.2 (which is about to be released.

[buildmsg.txt](https://github.com/jrincayc/ucblogo-code/files/8950126/buildmsg.txt)

**Comment by dmalec** [comment]
Based on a quick scan, it does look like the new constants are all present in wxWidgets 3.0.5, so I think we can update in preparation for 3.2 without breaking the existing build.

Thinking out loud a bit - I wonder if it's worth reserving this issue for fixing the deprecation warnings with wxWidgets 3.2 and fixing the other warnings under issue #20 .

**Comment by pmetzger** [comment]
> Thinking out loud a bit - I wonder if it's worth reserving this issue for fixing the deprecation warnings with wxWidgets 3.2 and fixing the other warnings under issue https://github.com/jrincayc/ucblogo-code/issues/20 .

No opinion. I am sure either way things will be fine.

**Comment by jrincayc** [comment]
@dmalec  Thank you for fixing this, @pmetzger thank you for reporting this.
