### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jrincayc** [jrincayc/ucblogo-code#14]
The README has some old information that needs updating before the release.  Also, consider combining README and README.md

**Comment by Alexey-Slyusar** [comment]
Hello @jrincayc,

Please let me know if I may help with the issue.

I have some free time tomorrow and I think that I can summarise changes made by 9 finished pull requests and use this info to update README. 
Next I can combine README and README.md.
Thus I can provide you with ready for review draft of the combined document (README.md).

But If you think that it is better to make the update without any help - it is okay. I just want you to know that it will be pleasure for me to make something helpful for this project, something that I am able to do, like, say, documentation updates when I have some free time.
Having free time is not that common for me, alas.

You can take a look at my text related work here:
https://github.com/PDP-10/its/blob/master/doc/logo.md

**Comment by jrincayc** [comment]
@Alexey-Slyusar If you still have time feel free to work on combining the two README files.  Note that windows, mac and linux now use wxWidgets 3.0

Thanks.

**Comment by Alexey-Slyusar** [comment]
Yes, I have.

Thank you.

вс, 22 дек. 2019 г. в 23:14, Joshua Cogliati <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
@jrincayc please take a look at the combined document:
https://github.com/Alexey-Slyusar/ucblogo-code/blob/master/README.md

If you accept overall structure of the document, I'll make a pull request for more detailed review.

Thank you.

**Comment by brianharvey** [comment]
Looks great except you have to spell my name right!  :-)

**Comment by Alexey-Slyusar** [comment]
As an alternative option, you can use the combined file partly or the whole
as you wish without any pull request at all.

I see that the code is ready for new release and I am afraid that my
activity may be bothering, rather than helpful.
I don’t want to make a problem.

пн, 23 дек. 2019 г. в 09:49, Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by brianharvey** [comment]
Actually it'd be good if the readme preserved this text from my version:

The interpreter was written primarily by Daniel Van Blerkom, Brian Harvey,
Michael Katz, and Douglas Orleans.  Thanks to Fred Gilham for the X11 code.
Emacs logo-mode by Hrvoje Blazevic.

... and feel free to add Josh!

**Comment by Alexey-Slyusar** [comment]
Dr. Harvey, my apologies for the misspelling.
I’ll fix this unfortunate fact in a moment.
Sorry.


пн, 23 дек. 2019 г. в 15:36, Brian Harvey <notifications@github.com>:

**Comment by jrincayc** [comment]
> Emacs logo-mode by Hrvoje Blazevic.
Hm, the Emacs logo-mode got removed between 5.5 and 6.0  I was wondering why and if I should add it back?

**Comment by Alexey-Slyusar** [comment]
fixed and added.

https://github.com/Alexey-Slyusar/ucblogo-code/blob/master/README.md


пн, 23 дек. 2019 г., 15:47 Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by brianharvey** [comment]
Oh, it's because the wxwidgets version has its own built-in editor rather than relying on an external one.  It wouldn't hurt for it to be runnable in an Emacs window, but it would have to notice that and not start up the wx stuff.

**Comment by jrincayc** [comment]
> fixed and added. https://github.com/Alexey-Slyusar/ucblogo-code/blob/master/README.md пн, 23 дек. 2019 г., 15:47 Alexey Slyusar <aleksey.slyusar@gmail.com>:
> […](#)

Thank you, it generally looks good.

**Comment by Alexey-Slyusar** [comment]
I am not able to make a pull request at the moment. Have a meeting at work.
That is why I wrote about another option above in the thread.
But if this can wait, l’ll make a pull request in two hours or so.

пн, 23 дек. 2019 г. в 16:13, Joshua Cogliati <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
> Thank you, it generally looks good.

A pleasure :-)

пн, 23 дек. 2019 г. в 16:31, Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by jrincayc** [comment]
Closed by #18
