### ISSUE TITLE
MacOS ready-to-run version fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by GrantMeStrength** [jrincayc/ucblogo-code#161]
The jpeg library is not present, and when manually built and installed, it is an ARM but USBLogo needs an X86 version (I am assuming that the UCBLogo binary is X86 and running under rosetta on the Apple Silicon Mac). Best fix would be an Apple Silicon specific build? Or some guidance on compiling USBLogo for Apple Silicon Mac?

**Comment by dmalec** [comment]
Issue #158 has some notes on the core problem and a dmg (please see comment: https://github.com/jrincayc/ucblogo-code/issues/158#issuecomment-1436071882) built using the updated GitHub pipeline (which configures wxWidgets to not have a link to those libraries).

I'll need to double check what I did when tracking that issue down - I had originally assumed it was an Apple Silicon issue and then shifted my focus as I realized the more general problem was that wxWidgets had picked up unintended dependencies during its build (those libraries are present on the GitHub build nodes; but, they shouldn't be a required dependency for running UCBLogo). I'll see if I got to a full Apple Silicon native build of UCBLogo + wxWidgets and if so what steps I followed.

**Comment by GrantMeStrength** [comment]
Thanks! Looking forward to getting it running again.

**Comment by dmalec** [comment]
You're welcome, glad to help :)

**Comment by jrincayc** [comment]
Hopefully this is fixed in 6.2.4: https://github.com/jrincayc/ucblogo-code/releases/tag/version_6.2.4

**Comment by jasonsikes** [comment]
Hashtag-works-for-me!

Just wanted to verify that 6.2.4 (downloaded from the link in the comment by @jrincayc above) works on my Mac. It's an M2 Silicon. 

While I do have Homebrew installed, I tested with these steps:

1. Comment out Homebrew references in .zshrc.
2. Move "/opt/homebrew" to "/opt/homebrew_aside".
3. Reboot.
4. Run UCBLogo from the Finder.

I think this is safe to close.
