### ISSUE TITLE
weird cross-references in texi-based manual

### ISSUE THREAD

**Issue by brianharvey** [jrincayc/ucblogo-code#24]
Look up PENREVERSE in the manual.  You'll find a cross-reference to REVERSE, but the two have nothing to do with each other.  (The first is in Graphics and the second is a list operation.)  There are bunches like that.

Also, in the HTML version, the very first line is full of TeX commands.

**Comment by jrincayc** [comment]
I agree this is a problem.  Another example is PENERASE and ERASE.  Even more bizarre is PENMODE has a crossrefernce to ERASE.

**Comment by jrincayc** [comment]
So these are in the Pen Queries section and the Pen and Background Control section.

Also, the HTML version needs to be checked to fix the first line.

**Comment by Alexey-Slyusar** [comment]
I’ll try to take a look at and resolve this issue next weekend. Is it okay?

**Comment by brianharvey** [comment]
I fixed some, maybe all, while adding the OOP stuff, so this may be obsolete except for the part about the first line.

**Comment by jrincayc** [comment]
The first line in the HTML manual now looks fine, so closing.
