### ISSUE TITLE
Error message/crash if unreasonably large value is given as first input to built-in procedure FILLED.

### ISSUE THREAD

**Issue by zigggit** [jrincayc/ucblogo-code#40]
UCB Logo 6.1 running on Linux.

If the colour value given to FILLED is too large, Logo sometimes exits with SIGTRAP or SIGSEGV or generates a pop-up error message that reports './src/gtk/colour.cpp(241): assert "IsOk()" failed in GetColor(): invalid colour' and gives the options Stop or Continue. Selecting either of these then usually results in Logo exiting immediately with SIGTRAP or SIGSEGV. Occasionally, Logo does not exit straight away after selecting Stop or Continue, but apparently continues to function normally for a while and then without further warming terminates with SIGTRAP or SIGSEGV. The precise behaviour seems unpredictable.

I don't know exactly how large the colour value has to be to cause this problem, but I find that 500 seems not to and 600 has every time I've tried it. Example:

  filled 600 [fd 100 rt 90 fd 150]

Clearly 600 is an unreasonably large value to give to FILLED, but I think it should not cause Logo to crash. I note that SETPC does not have this problem, values > 1000000 work perfectly well and get mapped to one of the colours.

P.S. I hope you don't mind me logging all these bugs and oddities. I've recently started experimenting with Logo and am finding quite a lot of rough edges in UCB Logo. Still, it's proving to be useful and educational.

**Comment by jrincayc** [comment]
I apologize for not having time to fix these immediately.  But I do greatly appreciate every bug that you (and others) describe in enough detail that I can replicate them. I am not sure when I will have time to fix them, but possibly other people might have time to submit a patch (and I will try and review and merge any correct fixes quickly).  If no one else gets to them first, I will work on fixing them as I have time.

**Comment by zigggit** [comment]
That's good to know. I might try to have a closer look into the cause of some of these problems myself. I'm hampered a bit by by not having done much C++ programming (I'm very familiar with C) and I know almost nothing about wxWidgets. However, the biggest impediment is that there appears to be no documentation on UCB Logo's internals, not even an overview of its general architecture. Just a few pages of this sort of documentation, if done well, would be extremely useful and I would think be the biggest contribution that could be made to making UCB Logo maintainable in the long run.

**Comment by brianharvey** [comment]
The main documentation is in the file plm (stands for "Program Logic Manual" which is what they called them when I worked for IBM as a child) and a flowchart in evaluator.ps.  The documentation of what's where is in the file tags, which is an Emacs tags file.  But really the best documentation is the Explicit Control Evaluator in SICP Chapter 5.

**Comment by zigggit** [comment]
It appears that SETPC uses a macro called set_pen_color and this (at least for the wxWidgets version of it) obtains the colour value to be used based on the colour value input modulo NUMCOLORS, whereas FILLED uses the input value directly.

I'm not certain this is the best approach, but changing line 1477 of graphics.c to the following seems to resolve the problem:

  color = getint(val) % NUMCOLORS;

It might be worth checking other procedures that take a colour input for similar problems. I have just looked at SETBG and it appears to do the right thing.

**Comment by pahihu** [comment]
Hi,

I’ve submitted a fix for FILLED, your proposed solution resolves only your case (ie. call FILLED with a color
index greater than NUMCOLORS).

pahihu
