### ISSUE TITLE
Can't select/copy text

### ISSUE THREAD

**Issue by jasonsikes** [jrincayc/ucblogo-code#44]
On MacOS when I try to select text one of two things happens:
1. Nothing
2. The application crashes.

The chances of which one will occur seem to be about 50/50.

On Windows I can select and copy, but when I paste to Wordpad the text is unrecognizable.

**Comment by brianharvey** [comment]
For me, it seems to crash if and only if I try to select text on the first line ("Welcome to Logo").

**Comment by dmalec** [comment]
I'm seeing the same behaviors above, I have a proposed PR https://github.com/jrincayc/ucblogo-code/pull/58 
The code change looks like it addresses the issue with populating the clipboard (at least on OSX Catalina 10.15.6 with wxWidgets 3.0.5)

**Comment by jasonsikes** [comment]
This works!

It looks a little weird when I select text, but I think that's an unrelated and minor issue.

Closing as fixed. Thank you!
