### ISSUE TITLE
Wrong line is output when bad TAG is used in GOTO

### ISSUE THREAD

**Issue by jasonsikes** [jrincayc/ucblogo-code#50]
When I have this procedure:
```
to proc
goto "tag2
print [this shouldn't print]
tag "tag1
print [this shouldn't print, either]
end
```
and then call it, I get an error. That is expected. What is surprising is the line that is output showing where UCBLogo thinks the error occurred.

```
EXPECTED: ---------------------------------------------
goto doesn't like tag2 as input  in proc
[goto "tag2]


OUTPUT: -----------------------------------------------
goto doesn't like tag2 as input  in proc
[print [this shouldn't print, either]]
```

**Comment by brianharvey** [comment]
Oh, right, Logo reads to the end of the procedure without finding a matching tag, so it thinks the error is at the end of the procedure.  Sigh.
