### ISSUE TITLE
modifications to a list don't change its runparsing.

### ISSUE THREAD

**Issue by jasonsikes** [jrincayc/ucblogo-code#53]
When a list is run and then modified and then run again, the changes are ignored during execution.

Example 1:
```
make "a [print "hello]
run :a
.setbf :a ["hi]
run :a


EXPECTED: ---------------------------------------------
hello
hi


OUTPUT: -----------------------------------------------
hello
hello
```
Example 2:
```
make "a [show [hello]]
run :a
.setfirst :a "print
run :a


EXPECTED: ---------------------------------------------
[hello]
hello


OUTPUT: -----------------------------------------------
[hello]
[hello]
```

**Comment by jasonsikes** [comment]
I decided this *really* should not be considered an issue.

* I understand that this is a side effect of optimization. A list is parsed before it is run. A vast majority of the time we don't need to parse it again. This issue is an edge case where a user would be running self-modifying code. I have never written self-modifying code nor felt the need to.
* I was implying that UCBLogo could reparse a list if the list is modified. However, after some thought I realized if we modify a list without modifying the head of the list, it would be difficult for the parsed structure to be alerted to the change. For example:

```
? make "a [print "hello]
? run :a
hello
? make "b butfirst :a
? .setfirst :b "hi
? run :a
hello
? show :a
[print hi]
```

I don't think there is an efficient way to automatically alert *a* that a change has been made somewhere in its tail.

**Comment by brianharvey** [comment]
Logo _does_ do the right thing if the text of a _procedure_ is modified, even during the running of the procedure, as long as the modification affects a different line.  But I agree, there's no good way to notify a pair upstream from the modified one of a change.  Or, umm, I suppose that when a list is runparsed, every pair in it could have its .object set to something that points to the head(s) of the instruction(s) containing it...  But we've gone all this time without that feature.
