### ISSUE TITLE
EDIT omits " upon close & accept change (v6.1 running on MacOS 10.13.6)

### ISSUE THREAD

**Issue by kgochko** [jrincayc/ucblogo-code#72]
download Logo v6.1 from https://people.eecs.berkeley.edu/~bh/logo.html
intall in /Applications
click on UCB-Logo Icon

to "junk
  pr "FOO
end

junk
FOO

po "junk
to junk
  pr "FOO
end

ed "junk
  to junk
     pr "foo
  end
close & accept changes

po "junk
  to junk
     pr     foo
  end

junk
I don't know how. to.    foo   in junk

ed "junk
  to junk
    pr "bar
  end
close & accept changes

save f
erall
load f

po "junk
to junk
  pr   bar
end
ed "junk
to junk
  pr "bar
end

**Comment by brianharvey** [comment]
I can't duplicate this on MacOS 10.13.  What platform are you on?

**Comment by kgochko** [comment]
Mid 2010 21.5” iMac running under macOS v10.13.6
3.06 GHz Intel Core i3
16 GB 1333 MHz DDR3
500 GB SSD
ATI Radeon HD 4670 256 MB

I’ll try re-downloading & re-installing Logo to see what happens.

**Comment by kgochko** [comment]
I deleted the old version of USB-Logo.
re-downloaded v6.1 macOS version from https://people.eecs.berkeley.edu/~bh/logo.html
unpacked (but didn't install) USBLogo.dmg
clicked on the USBLogo icon
got the exact same behavior.

I am able to use an external editor (Emacs) & use the LOAD command to get working procedures.

**Comment by dmalec** [comment]
I can replicate closely enough on OSX 10.15.7 I suspect I'm seeing the same underlying issue.

If I go to *System Preferences* -> *Keyboard* -> *Text* and toggle the *Use smart quotes and dashes* setting to *checked*, I see similar behavior:
```
? to junk
> pr "FOO
> end
junk defined
? junk
FOO
? po "junk
to junk
pr "FOO
end

? ed "junk
```
*Go into internal editor and just change `FOO` to `foo`*
```
to junk
pr “foo
end
```
*Close and accept changes*
```
? po "junk
to junk
pr    foo
end

? junk
I don't know how  to    foo  in junk
[pr    foo]
? 
```

Interestingly, the extended space in front of foo copy/pastes as `â` (supporting smart quotes being the issue).

If I toggle *Use smart quotes and dashes* to *unchecked* (which is how I usually run), editing works as expected.

**Comment by kgochko** [comment]
That solved the problem (Smat Quotes was checked -- I didn't even know it existed)
thanks for the help

**Comment by dmalec** [comment]
You're welcome, no worries :)
