### ISSUE TITLE
EDALL crashes UCBLogo on MacOS if no procedures defined

### ISSUE THREAD

**Issue by derekprior** [jrincayc/ucblogo-code#89]
My Son is learning Logo, following along with the Secret Coders book series. We've run into an issue with the `edall` command in UCBLogo 6.2 on MacOS. We got to a point in the tutorials where they introduced `TO` and suggested we enter the procedure using the `EDALL` command. When we enter `EDALL`, UCBLogo crashes.

I reproduced this behavior on two macs across three user accounts running two different OS X versions (High Sierra and Catalina). It also exists in UCBLogo 6.1.

If I first use the REPL interface and define a command there, then I'm able to use `EDALL` to edit or add to it.

**Comment by brianharvey** [comment]
Doesn't happen if compiled without wxWidgets.  (I have one of each on my mac, both 6.2.)

(Quibble:  In Logo it's not a REPL, just a Read-Eval loop.  If you want something printed you say PRINT explicitly.)

**Comment by brianharvey** [comment]
P.S.  It works if a variable is defined; only if CONTENTS is [[] [] []] does it crash.  Works in Windows with wxWidgets.

**Comment by dmalec** [comment]
I believe this has the same root cause as issue #33 - the editor calling `SetStyle` with a negative starting index. Seems like this results in different behaviors on Linux, OSX, and Windows. With the layer of indirection due to it being in an event handler, this was an interesting puzzle :)
